spring:
  config:
    activate:
      on-profile: dev

  jpa:
    show-sql: true

logging:
  level:
    com.github.superz97.githubactivitytracker: TRACE
    org.springframework.data.redis: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE