spring:
  application:
    name: github-activity-tracker

  datasource:
    url: jdbc:postgresql://localhost:5432/github_tracker
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
    schemas: public
    table: flyway_schema_history
    validate-migration-naming: true
    out-of-order: false
    placeholder-replacement: true
    placeholders:
      schema_name: public

  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  shell:
    interactive:
      enabled: true
    script:
      enabled: false
    command:
      version:
        enabled: false

github:
  api:
    base-url: https://api.github.com
    token:

logging:
  level:
    root: INFO
    com.github.tracker: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

webclient:
  timeout:
    connection: 5000
    read: 10000
    write: 5000

  config:
    activate:
      on-profile: dev